recon: null
engineering: true
collections: []
dish: null
car:
  name: null
  country: ''
extras:
- Strike_Stormy_1
- Strike_Stormy_3
- Strike_Stormy_2
- Strike_Stormy_4
- Strike_Stormy_5
- Strike_Stormy_6
